# Generated by Django 2.2.3 on 2019-08-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190801_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dispatched_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
