# Generated by Django 2.2.3 on 2019-08-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190801_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='menu_set',
            field=models.ManyToManyField(through='core.Order', to='core.Menu'),
        ),
    ]
