# Generated by Django 2.2.3 on 2019-08-02 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190802_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='ambient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.Ambient'),
        ),
    ]
