# Generated by Django 2.2.3 on 2019-08-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190802_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='menu_set',
        ),
        migrations.AddField(
            model_name='table',
            name='menus',
            field=models.ManyToManyField(related_name='tables', through='core.Order', to='core.Menu'),
        ),
    ]
