# Generated by Django 2.2.3 on 2019-08-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190802_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
